plugins {
	id 'java'
	id 'org.springframework.boot' version '2.7.8'
	id 'io.spring.dependency-management' version '1.0.15.RELEASE'
}

group = 'miraeasset-mobile'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'

	//lombok관련
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'


	//db관련
	runtimeOnly 'com.h2database:h2'
	runtimeOnly ('com.mysql:mysql-connector-j') //특히 이 부분 application.yml에서 에러 해결

	//test
	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	//swagger
	implementation 'org.springdoc:springdoc-openapi-ui:1.6.9'


	//json Parsing
//	implementation 'com.googlecode.json-simple:json-simple:1.1.1'
//	compileOnly 'com.google.code.gson:gson:2.8.2'
	implementation group: 'org.json', name: 'json', version: '20201115' // 국가 인증 api parsing에 활용
	implementation 'net.sf.json-lib:json-lib:2.4:jdk15' //json-lib : list to json


	//redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'


	//jwt
	// jwt dependency
	implementation group: 'io.jsonwebtoken', name: 'jjwt-api', version: '0.11.2'
	implementation group: 'io.jsonwebtoken', name: 'jjwt-impl', version: '0.11.2'
	implementation group: 'io.jsonwebtoken', name: 'jjwt-jackson', version: '0.11.2'


	//oauth
//	implementation("org.springframework.boot:spring-boot-starter-oauth2-client")


	//spring security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.security:spring-security-test'



	//sms 문자인증 - coolsms
	compileOnly group: 'net.nurigo', name: 'javaSDK', version: '2.2'


}

tasks.named('test') {
	useJUnitPlatform()
}
