api:
  key: "시세정보 조회 api - key"
  url: https://apis.data.go.kr/1160100/service/GetStockSecuritiesInfoService

jwt:
  key: "jwt 암호화 key : https://8gwifi.org/jwsgen.jsp 직접 생성가능(Shared secret) "

coolsms:
  api-key: "api key"
  api-secret: "secret key"
  from-number: "from number"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{url}:{port}/{dbname}?serverTimezone=Asia/Seoul
    username: "userName"
    password: "password"

  redis:
    host: {url}
    port: {port(default:6379)}
  cache:
    type: redis