api:
  data-go-kr:
    key: "주식 시세 정보 api(data.go.kr) - key "
    url: https://apis.data.go.kr/1160100/service/GetStockSecuritiesInfoService
  yahoo-finance:
    key: "주식 시세 정보 api(yh finance) - key"
    yh-url: https://yfapi.net

jwt:
  key: "jwt 암호화 key : https://8wifi.org/jwsgen.jsp : Shared secret(직접 생성가능)"

coolsms:
  api-key: "cool sms key"
  api-secret: "secret key"
  from-number: "from number"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{url}:{port}/{dbname}?serverTimezone=Asia/Seoul
    username: "userName"
    password: "password"
  redis:
    host: {host}
    port: {port}
  cache:
    type: redis
