api:
  key: {openAPI 시세정보조회 key}
  url: {openAPI 시세정보조회 url}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{url}:{port}/{db_name}?serverTimezone=Asia/Seoul
    username: {username}
    password: {password}